### ISSUE TITLE
Multiplayer ideas/checklist

### ISSUE THREAD

**Issue by BeefEX** [Anuken/Mindustry#37]
If we want to add multiplayer, it is best to add it as early as possible as it's the least work. But before work on it can begin we have to decide on a lot of stuff.

- [x] Framework - going with something custom or with an 3rd party solution
- [x] Architecture - Probably client-server
- [x] Structure and protocol

**Comment by BeefEX** [comment]
In my opinion we could borrow a lot from the way Minecraft is doing multiplayer since the design is almost the same (tile entities for example). The way updates are handled would have to probably change a bit for that though.

I think we should go with a custom "framework", we can design a custom "protocol" that way which would help with performance, but it might not be neccesary.

**Comment by BeefEX** [comment]
Closing for now. Proof of concept is done.
